# Site settings
title: Ryan Drew
email: info@ryanrdrew.com
description: > # this means to ignore newlines until "baseurl:"
  CCIS Student at Northeastern Unversity.
description2: Find me on Github <a href="https://github.com/ryandrew14">here</a> and Keybase <a href="https://keybase.io/ryandrew">here</a>
  or email me <a href="mailto:mail@ryanrdrew.com">here</a>.
baseurl: "" # the subpath of your site, e.g. /newpath-for-emping
url: "http://ryanrdrew.com" # the base hostname & protocol for your site
github_username:  ryandrew14
GoogleAnalytics: UA-xxxxxx-x

twitter:
  username: ryandrew8
facebook:
  app_id:
  publisher:

sass:
    style: compressed

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

defaults:
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:title'}}

include:
  - _pages

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock

paginate: 12
paginate_path: '/blog/:num'
